# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
        with:
          node-version: 11
          
      - name: Installing packages
        run: npm install
        
      - name: Build Gridsome site
        run: yarn build
        
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: cd https://github.com/yogicse12/curriculam-vitae.git; git pull; hugo; cp -r ./dist/* home/deploy/cv/; rm -rf ./dist
